<?php

/**
 * This phpFile is auto-generated.
 */

namespace Totaldev\TgSchema\Message;

use Totaldev\TgSchema\Dice\DiceStickers;
use Totaldev\TgSchema\TdSchemaRegistry;

/**
 * A stake dice message. The dice value is randomly generated by the server.
 */
class MessageStakeDice extends MessageContent
{
    public const string TYPE_NAME = 'messageStakeDice';

    public function __construct(
        /**
         * The animated stickers with the final dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known.
         */
        protected ?DiceStickers $finalState,
        /**
         * The animated stickers with the initial dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known.
         */
        protected ?DiceStickers $initialState,
        /**
         * The Toncoin amount that was gained from the roll; in the smallest units of the currency; -1 if the dice don't have final state yet.
         */
        protected int           $prizeToncoinAmount,
        /**
         * The Toncoin amount that was staked; in the smallest units of the currency.
         */
        protected int           $stakeToncoinAmount,
        /**
         * The dice value. If the value is 0, then the dice don't have final state yet.
         */
        protected int           $value,
    ) {
        parent::__construct();
    }

    public static function fromArray(array $array): MessageStakeDice
    {
        return new static(
            finalState        : (isset($array['final_state']) ? TdSchemaRegistry::fromArray($array['final_state']) : null),
            initialState      : (isset($array['initial_state']) ? TdSchemaRegistry::fromArray($array['initial_state']) : null),
            prizeToncoinAmount: $array['prize_toncoin_amount'],
            stakeToncoinAmount: $array['stake_toncoin_amount'],
            value             : $array['value'],
        );
    }

    public function getFinalState(): ?DiceStickers
    {
        return $this->finalState;
    }

    public function getInitialState(): ?DiceStickers
    {
        return $this->initialState;
    }

    public function getPrizeToncoinAmount(): int
    {
        return $this->prizeToncoinAmount;
    }

    public function getStakeToncoinAmount(): int
    {
        return $this->stakeToncoinAmount;
    }

    public function getValue(): int
    {
        return $this->value;
    }

    public function setFinalState(?DiceStickers $value): static
    {
        $this->finalState = $value;

        return $this;
    }

    public function setInitialState(?DiceStickers $value): static
    {
        $this->initialState = $value;

        return $this;
    }

    public function setPrizeToncoinAmount(int $value): static
    {
        $this->prizeToncoinAmount = $value;

        return $this;
    }

    public function setStakeToncoinAmount(int $value): static
    {
        $this->stakeToncoinAmount = $value;

        return $this;
    }

    public function setValue(int $value): static
    {
        $this->value = $value;

        return $this;
    }

    public function typeSerialize(): array
    {
        return [
            '@type'                => static::TYPE_NAME,
            'final_state'          => (null !== $this->finalState ? $this->finalState->jsonSerialize() : null),
            'initial_state'        => (null !== $this->initialState ? $this->initialState->jsonSerialize() : null),
            'prize_toncoin_amount' => $this->prizeToncoinAmount,
            'stake_toncoin_amount' => $this->stakeToncoinAmount,
            'value'                => $this->value,
        ];
    }
}
