<?php

/**
 * This phpFile is auto-generated.
 */

namespace Totaldev\TgSchema\Message;

use Totaldev\TgSchema\Dice\DiceStickers;
use Totaldev\TgSchema\TdSchemaRegistry;

/**
 * A dice message. The dice value is randomly generated by the server.
 */
class MessageDice extends MessageContent
{
    public const string TYPE_NAME = 'messageDice';

    public function __construct(
        /**
         * Emoji on which the dice throw animation is based.
         */
        protected string        $emoji,
        /**
         * The animated stickers with the final dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known.
         */
        protected ?DiceStickers $finalState,
        /**
         * The animated stickers with the initial dice animation; may be null if unknown. The update updateMessageContent will be sent when the sticker became known.
         */
        protected ?DiceStickers $initialState,
        /**
         * Number of frame after which a success animation like a shower of confetti needs to be shown on updateMessageSendSucceeded.
         */
        protected int           $successAnimationFrameNumber,
        /**
         * The dice value. If the value is 0, the dice don't have final state yet.
         */
        protected int           $value,
    ) {
        parent::__construct();
    }

    public static function fromArray(array $array): MessageDice
    {
        return new static(
            emoji                      : $array['emoji'],
            finalState                 : (isset($array['final_state']) ? TdSchemaRegistry::fromArray($array['final_state']) : null),
            initialState               : (isset($array['initial_state']) ? TdSchemaRegistry::fromArray($array['initial_state']) : null),
            successAnimationFrameNumber: $array['success_animation_frame_number'],
            value                      : $array['value'],
        );
    }

    public function getEmoji(): string
    {
        return $this->emoji;
    }

    public function getFinalState(): ?DiceStickers
    {
        return $this->finalState;
    }

    public function getInitialState(): ?DiceStickers
    {
        return $this->initialState;
    }

    public function getSuccessAnimationFrameNumber(): int
    {
        return $this->successAnimationFrameNumber;
    }

    public function getValue(): int
    {
        return $this->value;
    }

    public function setEmoji(string $value): static
    {
        $this->emoji = $value;

        return $this;
    }

    public function setFinalState(?DiceStickers $value): static
    {
        $this->finalState = $value;

        return $this;
    }

    public function setInitialState(?DiceStickers $value): static
    {
        $this->initialState = $value;

        return $this;
    }

    public function setSuccessAnimationFrameNumber(int $value): static
    {
        $this->successAnimationFrameNumber = $value;

        return $this;
    }

    public function setValue(int $value): static
    {
        $this->value = $value;

        return $this;
    }

    public function typeSerialize(): array
    {
        return [
            '@type'                          => static::TYPE_NAME,
            'emoji'                          => $this->emoji,
            'final_state'                    => (null !== $this->finalState ? $this->finalState->jsonSerialize() : null),
            'initial_state'                  => (null !== $this->initialState ? $this->initialState->jsonSerialize() : null),
            'success_animation_frame_number' => $this->successAnimationFrameNumber,
            'value'                          => $this->value,
        ];
    }
}
