<?php

/**
 * This phpFile is auto-generated.
 */

namespace Totaldev\TgSchema\Local;

use Totaldev\TgSchema\TdObject;

/**
 * Represents a local file.
 */
class LocalFile extends TdObject
{
    public const string TYPE_NAME = 'localFile';

    public function __construct(
        /**
         * True, if the file can be deleted.
         */
        protected bool   $canBeDeleted,
        /**
         * True, if it is possible to download or generate the file.
         */
        protected bool   $canBeDownloaded,
        /**
         * If is_downloading_completed is false, then only some prefix of the file starting from download_offset is ready to be read. downloaded_prefix_size is the size of that prefix in bytes.
         */
        protected int    $downloadedPrefixSize,
        /**
         * Total downloaded file size, in bytes. Can be used only for calculating download progress. The actual file size may be bigger, and some parts of it may contain garbage.
         */
        protected int    $downloadedSize,
        /**
         * Download will be started from this offset. downloaded_prefix_size is calculated from this offset.
         */
        protected int    $downloadOffset,
        /**
         * True, if the file is currently being downloaded (or a local copy is being generated by some other means).
         */
        protected bool   $isDownloadingActive,
        /**
         * True, if the local copy is fully available.
         */
        protected bool   $isDownloadingCompleted,
        /**
         * Local path to the locally available file part; may be empty.
         */
        protected string $path,
    ) {}

    public static function fromArray(array $array): LocalFile
    {
        return new static(
            canBeDeleted          : $array['can_be_deleted'],
            canBeDownloaded       : $array['can_be_downloaded'],
            downloadOffset        : $array['download_offset'],
            downloadedPrefixSize  : $array['downloaded_prefix_size'],
            downloadedSize        : $array['downloaded_size'],
            isDownloadingActive   : $array['is_downloading_active'],
            isDownloadingCompleted: $array['is_downloading_completed'],
            path                  : $array['path'],
        );
    }

    public function getCanBeDeleted(): bool
    {
        return $this->canBeDeleted;
    }

    public function getCanBeDownloaded(): bool
    {
        return $this->canBeDownloaded;
    }

    public function getDownloadOffset(): int
    {
        return $this->downloadOffset;
    }

    public function getDownloadedPrefixSize(): int
    {
        return $this->downloadedPrefixSize;
    }

    public function getDownloadedSize(): int
    {
        return $this->downloadedSize;
    }

    public function getIsDownloadingActive(): bool
    {
        return $this->isDownloadingActive;
    }

    public function getIsDownloadingCompleted(): bool
    {
        return $this->isDownloadingCompleted;
    }

    public function getPath(): string
    {
        return $this->path;
    }

    public function setCanBeDeleted(bool $value): static
    {
        $this->canBeDeleted = $value;

        return $this;
    }

    public function setCanBeDownloaded(bool $value): static
    {
        $this->canBeDownloaded = $value;

        return $this;
    }

    public function setDownloadOffset(int $value): static
    {
        $this->downloadOffset = $value;

        return $this;
    }

    public function setDownloadedPrefixSize(int $value): static
    {
        $this->downloadedPrefixSize = $value;

        return $this;
    }

    public function setDownloadedSize(int $value): static
    {
        $this->downloadedSize = $value;

        return $this;
    }

    public function setIsDownloadingActive(bool $value): static
    {
        $this->isDownloadingActive = $value;

        return $this;
    }

    public function setIsDownloadingCompleted(bool $value): static
    {
        $this->isDownloadingCompleted = $value;

        return $this;
    }

    public function setPath(string $value): static
    {
        $this->path = $value;

        return $this;
    }

    public function typeSerialize(): array
    {
        return [
            '@type'                    => static::TYPE_NAME,
            'can_be_deleted'           => $this->canBeDeleted,
            'can_be_downloaded'        => $this->canBeDownloaded,
            'download_offset'          => $this->downloadOffset,
            'downloaded_prefix_size'   => $this->downloadedPrefixSize,
            'downloaded_size'          => $this->downloadedSize,
            'is_downloading_active'    => $this->isDownloadingActive,
            'is_downloading_completed' => $this->isDownloadingCompleted,
            'path'                     => $this->path,
        ];
    }
}
